import { Category } from '../../shared/src/types.js'

export const topicBank: Record<Category, string[]> = {
  finance: [
    'Stock market morning briefing',
    'Cryptocurrency market update',
    'Federal Reserve latest decisions',
    'Personal finance tips for beginners',
    'Real estate market trends',
    'Inflation and cost of living update',
    'Top performing ETFs this week',
    'Small business finance spotlight',
  ],
  tech: [
    'AI news and breakthroughs',
    'Big tech company updates',
    'New gadgets and hardware releases',
    'Cybersecurity threats this week',
    'Open source software spotlight',
    'Gaming hardware news',
    'Space tech and satellite updates',
    'Mobile app trends',
  ],
  gaming: [
    'Top trending games this week',
    'Upcoming game releases',
    'Esports results and highlights',
    'Indie game spotlight',
    'Gaming industry business news',
    'Retro gaming corner',
    'Game patch and update roundup',
    'Streamer and content creator news',
  ],
  news: [
    'World news morning briefing',
    'US domestic news update',
    'Science and health headlines',
    'Environment and climate update',
    'Politics roundup',
    'Sports headlines',
    'Entertainment and culture news',
    'Viral stories of the day',
  ],
  niche: [
    'Weird science facts',
    'History spotlight',
    'Deep dive: how everyday things work',
    'Unsolved mysteries corner',
    'Internet culture and memes explained',
    'Obscure world records',
    'Behind the scenes of major industries',
    'Future predictions and futurism',
  ],
}